meta_product_name: "Kinship, le réseau local au service de vos enfants."
meta_title: "Kinship"
meta_description: "Kinship, le réseau de confiance des partenaires et des parents, au service de la réussite du parcours scolaire et professionnel de leurs enfants."
meta_image: "cover.png" # should exist in`app/assets/images/`
